# Generated by Django 5.1 on 2024-08-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_money', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'my_delivery', 'verbose_name_plural': 'my_delivery'},
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(help_text='the courior name should have less than 50 characters', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery_app.courier'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_destiation', to='delivery_app.location', verbose_name='customer_addres'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_origin', to='delivery_app.location', verbose_name='delivery_code'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.wallet')),
            ],
        ),
        migrations.AlterField(
            model_name='courier',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery_app.wallet'),
        ),
    ]
