# Generated by Django 5.1 on 2024-09-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_delivery_options_courier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='courier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.courier'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_destiation', to='delivery_app.location'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_origin', to='delivery_app.location'),
        ),
    ]
