# Generated by Django 5.1 on 2024-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_remove_courier_name_remove_courier_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='restuarant_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
