# Generated by Django 5.1 on 2024-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_delivery_restuarant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
